language: rust
dist: trusty
sudo: required
rust: 
  - nightly

node_js:
  - stable

# Cache `cargo install`ed tools, but don't cache the project's `target`
# directory (which ends up over-caching and filling all disk space!)
cache:
  directories:
    - /home/travis/.cargo

env:
  - PATH=$HOME/purescript:$HOME/psc-package:$PATH

install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install node
  - nvm use node
  - rustup target add wasm32-unknown-unknown
  - (test -x $HOME/.cargo/bin/wasm-gc || cargo install wasm-gc)
  - (test -x $HOME/.cargo/bin/wasm-bindgen || cargo install wasm-bindgen)
  - TAG=v0.12.0
  - PSC_PACKAGE_TAG=v0.4.2
  - wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$TAG/linux64.tar.gz
  - tar -xvf $HOME/purescript.tar.gz -C $HOME/
  - chmod a+x $HOME/purescript
  - wget -O $HOME/psc-package.tar.gz https://github.com/purescript/psc-package/releases/download/$PSC_PACKAGE_TAG/linux64.tar.gz
  - tar -xvf $HOME/psc-package.tar.gz -C $HOME/
  - chmod a+x $HOME/psc-package
  - npm install
  - npm install -g pulp
  - psc-package install

script:
  - npm run test:jest
  - npm run test:pulp

after_success:
  - npm run bundle 

deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
