git:
  submodules: false # the submodules are just for demo and are loaded via url

language: node_js

node_js:
  - stable

install:
  - npm install
  - npm install pulp purescript psc-package
  - psc-package install

script:
  - npm run test

after_success:
  - npm run build

deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
